### ISSUE TITLE
Milestone 2 tracking issue

### ISSUE THREAD

**Issue by lukemarsden** [SAME-Project/same-project#123]
# Milestone 2

Testing on a few sample notebooks & fixing stuff that comes up
- [ ] Pytorch
- [ ] Tensorflow
- [ ] Sklearn

Get rid of everything in same.yaml that isn’t being used
- [ ] Tech debty old stuff, get rid of it
- [ ]  Prune them and same init with simple one for user

Requirements.txt support
- [ ] Parsing imports and pip installing them directly (no version control)
- [ ] Unless requirements are in image
- [ ] Same verify - Requirements checking

breakages:
- [ ] Serialization, variable goes missing?
- [ ] Model serialization issue can also be bad
- [ ] Lambda layers in roadsigns?

Exploding variables
- [ ] Unserializable
- [ ] Very large things (size limit in same.yaml)

Azure support, at least in CI?
- [ ] Can Dave get us an Azure account with a KFP cluster and an Azure backend?
- [ ] Or drop support if it’s too hard

**Comment by Bubblyworld** [comment]
I've ticked off the testing tensorflow/sklearn/pytorch boxes because we now have a pretty big test suite for them - currently most of the test suite is failing, will dig deeper and add issues for each one.

**Comment by Bubblyworld** [comment]
Closing as all the tasks are complete now.
